### PR TITLE
Add UnoCSS module

### PR DESCRIPTION
**Pull request by go4cas**
Adding the UnoCSS style library to the list of modules.

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
Hi @go4cas!

Thanks for your contribution 🥳!
It already looks pretty good to me, but I will ping @BracketJohn to have a final look over it!

**Comment by go4cas** [comment]
@BracketJohn ... anything else required from my side to get this merged?

**Comment by BracketJohn** [comment]
Hey @go4cas  👋 

Thanks for the patience - I first wanted to land some other restructurign and things to then discuss this.

In general, I like the addition and see it as a valid alternative to unoCSS. At this point I have two considerations I'd like to discuss / resolve with you:
- [ ] resolve merge-conflicts
- [ ] should we add a separate step to ask for CSS utility frameworks?

I think (1) is a no-brainer. So, focusing on (2): If we just add UnoCSS to the list of modules, it will mean that a user could select UnoCSS and TailwindCSS at the same time. Is therea use-case for that? I think in general the two conflict and its an either / or decision, right? So then we should add a new step to the CLI to ask for utility frameworks specifically.

**Comment by go4cas** [comment]
@BracketJohn ... I was thinking along the same lines. I recon, to be able to scale the modules selection going forward, each section should ideally be split into it's own prompt. Example:

**Select an ORM:**
◯ None
◉ Prisma

**Select an Auth Library:**
◯ None
◉ Nuxt Auth

**Select an Auth Library:**
◯ None
◉ Nuxt Auth

**Select a Type Safety Library:**
◯ None
◉ tRPC 10

**Select a UI Component Library:**
◯ None
◉ Naive UI
◯ PrimeVue

**Select a CSS Utility Library:**
◯ None
◉ Tailwind.css
◯ UnoCSS

I think this will allow adding new sections/modules easier going forward.

The user will have a few more prompts to work through - but, creating a new app is not something we'll do all that often.

Thoughts?

**Comment by BracketJohn** [comment]
Thanks! I'm unsure as it makes the CLI way more complex (e.g.: instead of having one step were you can select all modules, you do it in many steps so if you want to go back, you can't).

What's your take on this @nexxeln? (they are the author of `create-t3-app`, I had some convo with them, maybe they are willing to give their take ❤️ )

**Comment by nexxeln** [comment]
> What's your take on this @nexxeln? (they are the author of `create-t3-app`, I had some convo with them, maybe they are willing to give their take ❤️ )

I'm a big fan of UnoCSS and use it for most projects. It is definitely more "Vue aligned" as it's antfu's project. I think a prompt for using either tailwind or uno should be okay. We can ask the other questions like it is right now and just have the css framework prompt as a separate one.

As for replacing tailwind with uno, I'm not too sure about that because tailwind is already used in production by a lot of companies and is very stable whereas uno hasn't reached 1.0 yet.

**Comment by BracketJohn** [comment]
Awesome, thanks for your opinion @nexxeln ❤️ 

Then let's:
- [ ] add a step: "What CSS utility class library would you like to use?" -> Tailwind / Uno
- [ ] get the tests to pass

And we're ready to merge @go4cas (:

**Comment by BracketJohn** [comment]
sorry - as there's not progress here I'll close this PR for now. We can re-open it at any later point!

**Pull request closed without merging**
